#version: "3.8"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

services:
  postgres:
    image: postgres:15.4-alpine3.18
    container_name: postgres-tcc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tcc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tcc"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - net
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tcc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - net
    build:
      context: ../frontned/tcc-front/.
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_completed_successfully

  jenkins:
    container_name: jenkins-test-tcc
    image: jenkins/jenkins:latest-jdk21
    ports:
      - "8099:8080"
    privileged: true
    restart: on-failure
    environment:
      - httpsKeyStore=/var/lib/jenkins/certificate.pfx --httpsKeyStorePassword=passw@rd
      - TZ=America/Sao_Paulo

